name: broncorideshare
description: first bronco rideshare

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+1
  firebase_auth: ^0.14.0+5
  cloud_firestore: 0.12.9+4
  flutter_screenutil: ^0.5.3
  flat_icons_flutter: ^1.0.2
  cupertino_icons: ^0.1.2
  #dependencies for goolge map api
  google_maps_flutter: ^0.5.21+8
  flutter_map: any
  location: ^2.3.5
  google_maps_webservice: ^0.0.14
  http: ^0.12.0+2
  uuid: ^2.0.1
  geolocator: ^5.1.4+2
  provider: ^3.0.0+1
  geocoder: ^0.1.2
  flutter_google_places: ^0.2.3
  flutter_spinkit: "^3.1.0"
  geoflutterfire: any
  get_it: ^1.0.3+2
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image_02.png
fonts:
  - family: CustomIcons
    fonts:
      - asset: assets/CustomIcons.ttf

  - family: Poppins-Bold
    fonts:
      - asset: assets/Poppins-Bold.ttf

  - family: Poppins-Medium
    fonts:
      - asset: assets/Poppins-Medium.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
